name: "build"
on: [ "push" ]
jobs:
  build-ivy-intellij:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "11"
      - run: "bash ./scripts/build.sh"

